import { Capacitor } from "@capacitor/core";
import { registerPlugin } from "@capacitor/core";

export interface AliveCorRecordingResult {
  success: boolean;
  // Optional fields that native plugins can populate later
  heartRate?: number;
  diagnosisText?: string;
  pdfPath?: string;
}

export interface AliveCorSDKPlugin {
  /**
   * Start a 6‑lead ECG recording using AliveCor SDK.
   *
   * This expects a short‑lived JWT generated by your Kardia
   * auth server (see AliveCor docs). The native side is
   * responsible for initializing AliveCorKitLite with this JWT
   * and launching the turnkey recording UI.
   */
  startSixLeadRecording(options: {
    jwt: string;
    mainsFrequencyHz: 50 | 60;
    environment?: "sandbox" | "production";
  }): Promise<AliveCorRecordingResult>;
}

const NativeAliveCor = registerPlugin<AliveCorSDKPlugin>("AliveCorSDK");

class AliveCorSDKBridge {
  isNativePlatform(): boolean {
    return Capacitor.isNativePlatform();
  }

  /**
   * High‑level helper used by the 6‑channel ECG page.
   *
   * - `jwt` MUST come from your own auth server.
   * - `mainsFrequencyHz` should be 50 or 60 based on region.
   */
  async startSixLeadRecording(params: {
    jwt: string;
    mainsFrequencyHz: 50 | 60;
    environment?: "sandbox" | "production";
  }): Promise<AliveCorRecordingResult> {
    if (!this.isNativePlatform()) {
      console.warn(
        "[AliveCorSDKBridge] startSixLeadRecording is only available on native (iOS/Android)."
      );
      return {
        success: false,
      };
    }

    if (!params.jwt) {
      throw new Error("JWT token is required to start AliveCor recording");
    }

    try {
      const result = await NativeAliveCor.startSixLeadRecording({
        jwt: params.jwt,
        mainsFrequencyHz: params.mainsFrequencyHz,
        environment: params.environment ?? "sandbox",
      });
      return result;
    } catch (err) {
      console.error("[AliveCorSDKBridge] Failed to start 6‑lead recording:", err);
      return {
        success: false,
      };
    }
  }
}

export const aliveCorSDK = new AliveCorSDKBridge();

