import { Capacitor } from "@capacitor/core";
import { registerPlugin } from "@capacitor/core";

export interface AliveCorRecordingResult {
  success: boolean;
  heartRate?: number;
  diagnosisText?: string;
  determination?: string;
  sampleRate?: number;
  durationSeconds?: number;
  deviceType?: string;
  isInverted?: boolean;
  waveformLeads?: Record<string, number[]>;
  pdfPath?: string;
}

export interface AliveCorSDKOptions {
  jwt: string;
  mainsFrequencyHz: number;
  patientId?: string;
  environment?: string;
  bundleId?: string;
  isDebugMode?: boolean;
}

export interface AliveCorSDKPlugin {
  /**
   * Start a 6‑lead ECG recording using AliveCor SDK.
   *
   * This expects a short‑lived JWT generated by your Kardia
   * auth server (see AliveCor docs). The native side is
   * responsible for initializing AliveCorKitLite with this JWT
   * and launching the turnkey recording UI.
   */
  startSixLeadRecording(options: AliveCorSDKOptions): Promise<AliveCorRecordingResult>;

  initialize(options: {
    jwt: string;
    isDebugMode?: boolean;
  }): Promise<void>;

  getDeviceStatus(): Promise<{
    connected: boolean;
    deviceName: string;
    deviceId?: string;
    ready: boolean;
    bluetoothEnabled: boolean;
    batteryLevel?: number;
    statusText: string;
  }>;

  startScan(): Promise<void>;
  stopScan(): Promise<void>;
  connect(options: { deviceId: string }): Promise<{ success: boolean; deviceId: string; deviceName: string }>;
  requestPermissions(): Promise<{ bluetooth: string; audio: string }>;

  dispose(): Promise<void>;

  addListener(eventName: "deviceFound", listenerFunc: (data: { deviceName: string; deviceId: string; rssi: number }) => void): any;
  addListener(eventName: "deviceConnected", listenerFunc: (data: { success: boolean; deviceId: string; deviceName: string }) => void): any;
}

const NativeAliveCor = registerPlugin<AliveCorSDKPlugin>("AliveCorSDK");

class AliveCorSDKBridge {
  isNativePlatform(): boolean {
    return Capacitor.isNativePlatform();
  }

  /**
   * High‑level helper used by the 6‑channel ECG page.
   *
   * - `jwt` MUST come from your own auth server.
   * - `mainsFrequencyHz` should be 50 or 60 based on region.
   */
  async startSixLeadRecording(params: {
    jwt: string;
    mainsFrequencyHz: 50 | 60;
    environment?: "sandbox" | "production";
    patientId?: string;
    bundleId?: string;
  }): Promise<AliveCorRecordingResult> {
    if (!this.isNativePlatform()) {
      console.warn(
        "[AliveCorSDKBridge] startSixLeadRecording is only available on native (iOS/Android)."
      );
      return {
        success: false,
      };
    }

    if (!params.jwt) {
      throw new Error("JWT token is required to start AliveCor recording");
    }

    try {
      const result = await NativeAliveCor.startSixLeadRecording({
        jwt: params.jwt,
        mainsFrequencyHz: params.mainsFrequencyHz,
        environment: params.environment ?? "sandbox",
        isDebugMode: params.environment !== "production",
        patientId: params.patientId,
        bundleId: params.bundleId
      });
      return result;
    } catch (err: any) {
      console.error("[AliveCorSDKBridge] Failed to start 6‑lead recording:", err);
      return {
        success: false,
        diagnosisText: err?.message || "Recording failed"
      };
    }
  }

  async initialize(jwt: string, isDebug: boolean = false): Promise<void> {
    if (!this.isNativePlatform()) return;
    return NativeAliveCor.initialize({ jwt, isDebugMode: isDebug });
  }

  async getDeviceStatus() {
    if (!this.isNativePlatform()) {
      return { connected: false, deviceName: "", deviceType: "WEB", ready: false, bluetoothEnabled: false };
    }
    return NativeAliveCor.getDeviceStatus();
  }

  async startScan() {
    if (!this.isNativePlatform()) return;
    return NativeAliveCor.startScan();
  }

  async stopScan() {
    if (!this.isNativePlatform()) return;
    return NativeAliveCor.stopScan();
  }

  async connect(deviceId: string) {
    if (!this.isNativePlatform()) return { success: false, deviceId: "", deviceName: "" };
    return NativeAliveCor.connect({ deviceId });
  }

  /**
   * Request Bluetooth and Audio permissions required by the AliveCor SDK.
   */
  async requestPermissions(): Promise<void> {
    if (!this.isNativePlatform()) return;
    const status = await NativeAliveCor.requestPermissions();
    console.log("[AliveCorSDKBridge] Permission status:", status);
  }

  addListener(eventName: string, listenerFunc: Function) {
    if (!this.isNativePlatform()) return { remove: () => {} };
    return (NativeAliveCor as any).addListener(eventName, listenerFunc);
  }
}

export const aliveCorSDK = new AliveCorSDKBridge();

