//
//  ACKLocalizedString.h
//  AliveECG
//
//  Created by Jim Qin on 7/5/16.
//  Copyright © 2016 AliveCor Inc. All rights reserved.
//

#import <Foundation/Foundation.h>

#import <AliveCorKitLite/ACKTypes.h>

NS_ASSUME_NONNULL_BEGIN

// API for all localized strings. Some style guide protocols:
// - ensure that methods in the header file are organized in alphabetically ascending order.
// - if the localized string includes a format specifier, add the word 'format' in the method name.

/// > Warning: AliveCorKitLite internal.
@interface ACKLocalizedString : NSObject

+ (NSString *)nowSettingUp;
+ (NSString *)nowLetsStartByFinding;
+ (NSString *)enableBluetoothToConnect;
+ (NSString *)findMyDevice;
+ (NSString *)successKardiaMobileSetUp;
+ (NSString *)yourKardiaDeviceIsPaired;
+ (NSString *)touchTheElectrodesToWake;
+ (NSString *)tapTheTopTwoElectrodes;
+ (NSString *)unableToPairKardiaMobile6L;
+ (NSString *)makeSureBluetoothTurnedOn;
+ (NSString *)turnOnBluetoothToConnect6L;
+ (NSString *)turnOnBluetoothInSettingsToConnect6L;
+ (NSString *)kardiaMobile6LNotFound;
+ (NSString *)tryAgain;
+ (NSString *)cancel;
+ (NSString *)OK;
+ (NSString *)okay;
+ (NSString *)somethingWentWrong;
+ (NSString *)undo;
+ (NSString *)invert;
+ (NSString *)off;
+ (NSString *)on;
+ (NSString *)autoInvert;
+ (NSString *)learnMore;
+ (NSString *)minutesFormat;
+ (NSString *)minuteFormat;
+ (NSString *)secondsFormat;
+ (NSString *)automatic;
+ (NSString *)original;
+ (NSString *)enhanced;
+ (NSString *)none;
+ (NSString *)clinicianReviewNewline;
+ (NSString *)addNoteNewline;
+ (NSString *)close;
+ (NSString *)back;
+ (NSString *)next;
+ (NSString *)bpm:(nullable ACKLanguageType)lang;
+ (NSString *)sharePdf;
+ (NSString *)recordingInProgress;
+ (NSString *)keepYourFingersOnCompletesElectrodes;
+ (NSString *)keepYourFingersOnKardiaMobilesPads;
+ (NSString *)touchTheElectrodesToStartRecording;
+ (NSString *)aliveCorInstantAnalysisAlgorithmFindings;
+ (NSString *)normal;
+ (NSString *)supraventricularEctopy;
+ (NSString *)supraventricularEctopyDescription;
+ (NSString *)prematureVentricularContractions;
+ (NSString *)prematureVentricularContractionsDescription;
+ (NSString *)wideQRS;
+ (NSString *)wideQRSDescription;
+ (NSString *)indicatesNormalSinusRhythmWithNoRhythmOrHeartRateAbnomalitiesDetected;
+ (NSString *)bradycardia;
+ (NSString *)atrialFibrilliationWasNotDetectedAndYourHeartRateWasSlow;
+ (NSString *)tachycardia;
+ (NSString *)atrialFibrilliationWasNotDetectedAndYourHeartRateWasFast;
+ (NSString *)possibleAtrialFibrillation;
+ (NSString *)indicatesAtrialFibrillationAnIrregularHeartRhythm;
+ (NSString *)indicatesAtrialFibrillationAnIrregularHeartRhythm:(nullable ACKLanguageType)lang;
+ (NSString *)indicatesAtrialFibrillationAnIrregularHeartRhythmV2;
+ (NSString *)indicatesAtrialFibrillationAnIrregularHeartRhythmV2:(nullable ACKLanguageType)lang;
+ (NSString *)unclassified;
+ (NSString *)atrialFibrilliationWasNotDetectedAndYourEkgDoesNotFallUnder;
+ (NSString *)theEkgCouldNotBeReadLikelyDueToSignalNoise;
+ (NSString *)learnHowToRecordAGoodQualityEkg;
+ (NSString *)unreadable;
+ (NSString *)tooShort;
+ (NSString *)yourEkgRecordingMustbeAtLeast30Seconds;
+ (NSString *)noAnalysis;
+ (NSString *)thereIsNoInstantAnalysisForThisEkg;
+ (NSString *)theseArePotentialFindingsAndNotADiagnosis;
+ (NSString *)battery;
+ (NSString *)yourRecordingWillStartOnceContactOnElectrodes;
+ (NSString *)iNeedHelp;
+ (NSString *)toStartRecordingPlacePhoneOnCompleteCradle;
+ (NSString *)toStartRecordingV2PlacePhoneOnCompleteCradle;
+ (NSString *)singleLeadEKG;
+ (NSString *)sixLeadEKG;
+ (NSString *)yourRecordingWillStartOnceGoodContactTopElectrodes;
+ (NSString *)theCompleteDeviceTransmitsEKGData;
+ (NSString *)microphoneAccessIsRequiredForVoiceRecordingForNotes;
+ (NSString *)kardiaMobileTransmitsEKGData;
+ (NSString *)microphoneAccessIsRequired;
+ (NSString *)grantAccess;
+ (NSString *)updateSettings;
+ (NSString *)logoUp;
+ (NSString *)leftHand;
+ (NSString *)rightHand;
+ (NSString *)yourRecordingWillStartOnceGoodContactTopAndBottomElectrodes;
+ (NSString *)retry;
+ (NSString *)grantBluetoothAccess;
+ (NSString *)grantBluetoothAccessInSettings;
+ (NSString *)turnOnBluetoothToStartYourRecording;
+ (NSString *)turnOnBluetoothFromTheSettingsApp;
+ (NSString *)saveEkg;
+ (NSString *)recordAgain;
+ (NSString *)gotIt;
+ (NSString *)electricalInterferenceDetected;
+ (NSString *)pleaseUnplugYourChargerOrMoveAwayFromPowerOutlets;
+ (NSString *)connect;
+ (NSString *)connectToYourKardiaMobile6L;
+ (NSString *)tapConnectToSearchForYourKardia;
+ (NSString *)batteryLevelIsTooLow;
+ (NSString *)pleaseFollowInstructionsToReplaceTheBattery;
+ (NSString *)initializing;
+ (NSString *)connectingToDevice;
+ (NSString *)recordingComplete;
+ (NSString *)processing;
+ (NSString *)leftAnkleOrKnee;
+ (NSString *)noContact;
+ (NSString *)stabilizing;
+ (NSString *)goodContact;
+ (NSString *)done;
+ (NSString *)ekgStorageIsCurrentlyDisabled;
+ (NSString *)youHavePreviouslyDisabledStorageOfYourEkgRecordings;
+ (NSString *)allow;
+ (NSString *)audioErrorCouldNotRecordTitle;
+ (NSString *)audioErrorCouldNotRecordText;
+ (NSString *)exit;
+ (NSString *)recordEKG;
+ (NSString *)selectedDevice;
+ (NSString *)connectNewDeviceCammelCased;
+ (NSString *)thereIsNotEnoughStorageAvailableToCreateAnEkgRecordingYouHaveFormat;
+ (NSString *)cannotRecordEkg;
+ (NSString *)recordingSingleLeadEKG;
+ (NSString *)recordingSixLeadEKG;
+ (NSString *)moveAwayFromChargers;
+ (NSString *)recordingTooShortMessage;
+ (NSString *)recordingTooNoisyMessage;
+ (NSString *)unableToRecord;
+ (NSString *)kardiaMobileUsesHighFrequencySoundUnableToAccessMicrophone;
+ (NSString *)confirmRecording;
+ (NSString *)continueRecording;
+ (NSString *)cancelRecording;
+ (NSString *)thisUserIsNotAKardiaStationUser;
+ (NSString *)patient:(nullable ACKLanguageType)lang;
+ (NSString *)recorded:(nullable ACKLanguageType)lang;
+ (NSString *)heartRate:(nullable ACKLanguageType)lang;
+ (NSString *)duration:(nullable ACKLanguageType)lang;
+ (NSString *)tags:(nullable ACKLanguageType)lang;
+ (NSString *)notes:(nullable ACKLanguageType)lang;
+ (NSString *)kardiaAdvancedDeterminationIsDoneOnLead1:(nullable ACKLanguageType)lang;
+ (NSString *)kardiaDeterminationIsDoneOnLead1:(nullable ACKLanguageType)lang;
+ (NSString *)disclaimer:(nullable ACKLanguageType)lang;
+ (NSString *)pvcNoticeTitle:(nullable ACKLanguageType)lang;
+ (NSString *)pvcNoticeDetails:(nullable ACKLanguageType)lang;
+ (NSString *)rrNoticeTitle:(nullable ACKLanguageType)lang;
+ (NSString *)rrNoticeDetails:(nullable ACKLanguageType)lang;
+ (NSString *)averageBeatNoticeTitle:(nullable ACKLanguageType)lang;
+ (NSString *)averageBeatNoticeDetails:(nullable ACKLanguageType)lang;
+ (NSString *)mainsFrequency:(nullable ACKLanguageType)lang;
+ (NSString *)enhancedFilter:(nullable ACKLanguageType)lang;
+ (NSString *)notchFilter;
+ (NSString *)noneFilter;
+ (NSString *)standardFilter:(nullable ACKLanguageType)lang;
+ (NSString *)scale:(nullable ACKLanguageType)lang;
+ (NSString *)millimetersPerSecond:(nullable ACKLanguageType)lang;
+ (NSString *)millimetersPerMillivolt:(nullable ACKLanguageType)lang;
+ (NSString *)pdfCopyright:(nullable ACKLanguageType)lang;
+ (NSString *)pdfCopyrightFormatWithRecordingInfo:(nullable ACKLanguageType)lang;
+ (NSString *)pdfCopyrightForCoverPage:(nullable ACKLanguageType)lang;
+ (NSString *)pdfCopyrightWithYear:(NSString *)year andSoftware:(NSString *)software andUUID:(NSString *)uuid andLanguage:(nullable ACKLanguageType)lang;
+ (NSString *)pdfCopyrightWithYear:(NSString *)year andLanguage:(nullable ACKLanguageType)lang;
+ (NSString *)pageOfFormat:(nullable ACKLanguageType)lang;
+ (NSString *)kai30SecondsLimitCaution:(nullable ACKLanguageType)lang;
+ (NSString *)kai30SecondsLimitCautionKAIv2:(nullable ACKLanguageType)lang;
+ (NSString *)thereWasAnErrorCreatingTheEkgPDF;
+ (NSString *)passwordProtectPdf;
+ (NSString *)inOrderToProtectYourPrivacy;
+ (NSString *)password;
+ (NSString *)skip;
+ (NSString *)encryptingPdf;
+ (NSString *)ekgRecording:(nullable ACKLanguageType)lang;
+ (NSString *)greatSignal;
+ (NSString *)goodSignal;
+ (NSString *)weakSignal;
+ (NSString *)noSignal;

+ (NSString *)toStartRecordingPlaceFingersOnPads;
+ (NSString *)youWillNeedAKardiaMobile;
+ (NSString *)yourEKGTracingCannotBeDisplayed;
+ (NSString *)getKardiaMobile;
+ (NSString *)needHelp;
+ (NSString *)cannotDetectSignsOfHeartAttack;
//+ (NSString *)watchAlgorithmResultTypeUnclassified;
+ (NSString *)kardiaAdvancedDetermination:(nullable ACKLanguageType)lang;
+ (NSString *)kardiaDetermination:(nullable ACKLanguageType)lang;
+ (NSString *)determination:(nullable ACKLanguageType)lang;
+ (NSString *)amplitudeMiliVolt:(nullable ACKLanguageType)lang;
+ (NSString *)timeMSeconds:(nullable ACKLanguageType)lang;
+ (NSString *)rrSeconds:(nullable ACKLanguageType)lang;
+ (NSString *)timeSeconds:(nullable ACKLanguageType)lang;
+ (NSString *)provisioning;
+ (NSString *)kardiaCardTouchElectrodToStartRecording;
+ (NSString *)contactSupport;
+ (NSString *)connectToYourKardiaCard;
+ (NSString *)connectToYourDevice:(NSString *)deviceName;
+ (NSString *)viewTutorial;
+ (NSString *)contactCustomerCare;
+ (NSString *)customerCare;
+ (NSString *)connectNewDevice;
+ (NSString *)amberLight;
+ (NSString *)powerButton;
+ (NSString *)deviceUnavailableTitle;
+ (NSString *)deviceUnavailableMessage;
+ (NSString *)deviceOfflineTitle;
//+ (NSString *)deviceOfflineMessage;
+ (NSString *)recordedOn:(nullable ACKLanguageType)lang;
+ (NSString *)additionalTextToDisplay:(nullable ACKLanguageType)lang;
+ (NSString *)noAdditionalTextToDisplay:(nullable ACKLanguageType)lang;
+ (NSString *)noTagsToDisplay:(nullable ACKLanguageType)lang;
+ (NSString *)noNotesToDisplay:(nullable ACKLanguageType)lang;
+ (NSString *)citationMessage:(nullable ACKLanguageType)lang;
+ (NSString *)copyrightMessage:(nullable ACKLanguageType)lang;
+ (NSString *)confidentialNotice:(nullable ACKLanguageType)lang;
+ (NSString *)unknownText:(nullable ACKLanguageType)lang;
+ (NSString *)sexString:(nullable ACKLanguageType)lang;
+ (NSString *)dobString:(nullable ACKLanguageType)lang;
+ (NSString *)ekgRecordingOverviewString:(nullable ACKLanguageType)lang;
+ (NSString *)maleString:(nullable ACKLanguageType)lang;
+ (NSString *)femaleString:(nullable ACKLanguageType)lang;
+ (NSString *)guestString:(nullable ACKLanguageType)lang;
+ (NSString *)normalSinusRhythm;
+ (NSString *)determinationUnclassifiedDescription;
+ (NSString *)atrialFibrillation;
+ (NSString *)ekgLegend;
+ (NSString *)quotedNormalSinusRhythm;
+ (NSString *)quotedBradycardia;
+ (NSString *)quotedTachycardia;
+ (NSString *)quotedUnclassified;
+ (NSString *)quotedSupraventricularEctopy;
+ (NSString *)quotedPrematureVentricularContractions;
+ (NSString *)quotedPossibleAtrialFibrillation;
+ (NSString *)quotedAtrialFibrillation;
+ (NSString *)quotedWideQRS;
+ (NSString *)quotedUnreadable;
+ (NSString *)quotedTooShort;
+ (NSString *)quotedNoAnalysis;
+ (NSString *)newPairingAlertMessage;
+ (NSString *)warning;
+ (NSString *)proceed;
+ (NSString *)preparedFor:(nullable ACKLanguageType)lang;
+ (NSString *)age:(nullable ACKLanguageType)lang;
+ (NSString *)dateOfBirth:(nullable ACKLanguageType)lang;
+ (NSString *)singleLeadRecording:(nullable ACKLanguageType)lang;
+ (NSString *)sixLeadRecording:(nullable ACKLanguageType)lang;

@end

NS_ASSUME_NONNULL_END
