#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3 effective-5.10 (swiftlang-6.3.0.123.5 clang-2100.0.123.102)
#ifndef ALIVECORKITLITE_SWIFT_H
#define ALIVECORKITLITE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AliveCorKitLite",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#import <AliveCorKitLite/AliveCorKitLite.h>

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AliveCorKitLite",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// warning:
/// AliveCor internal use only.
SWIFT_CLASS("_TtC15AliveCorKitLite15ACInternalUtils")
@interface ACInternalUtils : NSObject
/// warning:
/// AliveCor internal use only
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) ACKLanguageType _Nullable defaultLanguageType;)
+ (ACKLanguageType _Nullable)defaultLanguageType SWIFT_WARN_UNUSED_RESULT;
+ (void)setDefaultLanguageType:(ACKLanguageType _Nullable)value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSCoder;
@class NSString;
@class NSBundle;
/// This class displays the information of the AliveCorKitLite including copyright, Kardia AI, and Universal Monitor versions.
SWIFT_CLASS("_TtC15AliveCorKitLite22ACKAboutViewController")
@interface ACKAboutViewController : UIViewController
- (nonnull instancetype)initWithIsEU:(BOOL)isEU OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

/// Displays the list of determinations supported by the Kardia application.
/// <code>ACKAlgorithmDeterminationsViewController</code> renders a read-only catalog of
/// Kardia AI findings (e.g., Sinus Rhythm, AFib, Bradycardia). The set of rows
/// adapts based on the provided <code>algorithmPackage</code> (e.g., <code>"kaiv2"</code> enables
/// additional v2 determinations).
SWIFT_CLASS_NAMED("ACKAlgorithmDeterminationsViewController")
@interface ACKAlgorithmDeterminationsViewController : UIViewController
/// Creates a new determinations view controller.
/// \param algorithmPackage The algorithm package identifier. Pass
/// <code>"kaiv2"</code> (case-insensitive) to enable Kardia AI v2 determinations;
/// all other values fall back to v1.
///
- (nonnull instancetype)initWithAlgorithmPackage:(NSString * _Nullable)algorithmPackage OBJC_DESIGNATED_INITIALIZER;
/// Unavailable. Use <code>init(algorithmPackage:)</code>.
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
/// Hides the navigation bar while the list is visible.
- (void)viewWillAppear:(BOOL)animated;
/// Restores the navigation bar when leaving the screen.
- (void)viewWillDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class NSDate;
@class FeatureModel;
/// Represents SDK configuration and partner-specific restrictions.
/// <code>ACKConfiguration</code> contains metadata received from the AliveCor
/// provisioning service, such as authorization expiration, supported
/// device entitlements, and Kardia AI version eligibility.
/// This object helps determine which SDK features are active for a
/// specific partner and when configuration refreshes are required.
SWIFT_CLASS("_TtC15AliveCorKitLite16ACKConfiguration")
@interface ACKConfiguration : NSObject
/// The date when the SDK authorization expires.
@property (nonatomic, copy) NSDate * _Nullable expirationDate;
/// The set of feature entitlements returned by the provisioning service.
@property (nonatomic, copy) NSArray<FeatureModel *> * _Nullable features;
/// The list of devices supported for the current partner configuration.
@property (nonatomic, readonly, copy) NSArray<ACKDeviceType> * _Nonnull supportedDevices;
/// Indicates whether the configuration should be refreshed.
/// Returns <code>true</code> if the phone-home interval has elapsed, or <code>false</code> otherwise.
@property (nonatomic, readonly) BOOL isStale;
/// The enumerated type of the current algorithm package.
/// Returns <code>.KAIV2</code> if <code>algVersion</code> equals <code>"kaiv2"</code> (case-insensitive), otherwise <code>.KAIV1</code>.
@property (nonatomic, readonly) ACKAlgorithmVersion algVersionType;
/// Indicates whether the configuration has expired.
/// Returns <code>true</code> if the current authorization is no longer valid,
/// or <code>false</code> if it is still active or authorization checks are disabled.
@property (nonatomic, readonly) BOOL hasExpired;
/// A textual summary of the configuration’s key values.
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15AliveCorKitLite14ACKEventBridge")
@interface ACKEventBridge : NSObject
+ (NSString * _Nonnull)recording SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)evaluation SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ACKWebLinks;
SWIFT_ENUM_FWD_DECL(NSInteger, ServerType)
/// An entry point for the SDK usage for AliveCorKitLite. The consumer must initialize this class during app startup with the accessToken fetched from Alivecor server. The access token is used to validate the authenticity of the partner. All interactions with the library will fail if this class is not configured.
/// <blockquote>
/// Warning: AliveCorKitLite internal.
///
/// </blockquote>
SWIFT_CLASS("_TtC15AliveCorKitLite20ACKManagerKardiaCore")
@interface ACKManagerKardiaCore : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) ACKManagerKardiaCore * _Nonnull sharedInstance;)
+ (ACKManagerKardiaCore * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
+ (void)setSharedInstance:(ACKManagerKardiaCore * _Nonnull)value;
@property (nonatomic) ACKLanguageType _Nullable defaultLanguageType;
/// The access token that is being used to authorize SDK usage.
@property (nonatomic, readonly, copy) NSString * _Nullable accessToken;
@property (nonatomic) BOOL isViewTutorialVisible;
/// The application’s name.
@property (nonatomic, readonly, copy) NSString * _Nullable appName;
/// The path to the directory where recorded ECG are stored.
@property (nonatomic, readonly, copy) NSString * _Nullable ecgFilesDirectory;
/// <ul>
///   <li>
///     If there is no configuration or the configuration is expired, please fetch ACKConfiguration from server by calling: <code>refreshConfigurationFromServer(completion:)</code>
///   </li>
/// </ul>
///
/// returns:
/// ACKConfiguration that defines configuration and/or restrictions specific to the SDK consumer.
@property (nonatomic, readonly, strong) ACKConfiguration * _Nullable localConfiguration;
/// Defines web links that would be used on the HUD screens.
@property (nonatomic, strong) ACKWebLinks * _Nullable links;
/// Tells whether the SDK is running in debug mode or not.
@property (nonatomic, readonly) enum ServerType serverType;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ServerType, open) {
  ServerTypeStaging = 0,
  ServerTypeProduction = 1,
};

@class NSError;
@interface ACKManagerKardiaCore (SWIFT_EXTENSION(AliveCorKitLite))
/// Returns the version of the SDK.
@property (nonatomic, readonly, copy) NSString * _Nullable version;
@property (nonatomic, readonly, copy) NSString * _Nullable buildNumber;
/// Initial configuration of the ACKManager. The function should be called only once in an application’s life cycle. Warning: Calling this method multiple times will have undetermined behaviors.  If an ACKConfiguration doesn’t exist or is expired, please call <code>refreshConfigurationFromServer(completion:)</code> to fetch ACKConfiguration.
/// \code
/// // Examples of refreshTokenClosure:
/// ACKManager.sharedInstance.configureWith(accessToken: "123", serverType: .staging) { completionHandler in
///    // Fetching new token from the server
///    // ...
///    completionHandler(token, nil)
/// }
///
/// \endcode\param accessToken an access token obtained from AliveCor backend.
///
/// \param serverType the server that the access token will be sent to.
///
/// \param refreshTokenClosure the closure will be called when the accessToken is expired and a new token is needed for continuously using the SDK.
///
- (void)configureWithAccessToken:(NSString * _Nonnull)accessToken serverType:(enum ServerType)serverType refreshTokenClosure:(void (^ _Nonnull)(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable)))refreshTokenClosure;
- (void)updateAccessToken:(NSString * _Nonnull)accessToken;
- (NSString * _Nonnull)algorithmPackageForCurrentKAI SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isKAIV2enabled SWIFT_WARN_UNUSED_RESULT;
/// Fetch ACKConfiguration from Alivecor backend with stored access token. If the access token is invalid, the ACKManagerKardiaCoreRefreshTokenClosure will be called.
- (void)refreshConfigurationFromServerWithCompletion:(void (^ _Nullable)(NSError * _Nullable, ACKConfiguration * _Nullable))completion;
/// Fetch ACKConfiguration from Alivecor backend with an access token.
- (void)refreshConfigurationFromServerWith:(NSString * _Nonnull)token completion:(void (^ _Nullable)(NSError * _Nullable, ACKConfiguration * _Nullable))completion;
/// Resets the paired device.
- (void)forgetDevice;
/// Returns supported recording devices.
- (NSArray<ACKDeviceType> * _Nonnull)supportedDevices SWIFT_WARN_UNUSED_RESULT;
/// Returns true if stored configuration is valid in order to use the SDK. If return false, please fetch a new ACKConfiguration from the server by calling: <code>refreshConfigurationFromServer(completion:)</code>
- (BOOL)isValidConfiguration SWIFT_WARN_UNUSED_RESULT;
/// A debug feature that allow host application to test it’s refresh token logic.
- (void)deleteAccessToken;
@end

/// <blockquote>
/// Warning: AliveCorKitLite internal.
///
/// </blockquote>
SWIFT_CLASS("_TtC15AliveCorKitLite18ActivityLevelModel")
@interface ActivityLevelModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// <blockquote>
/// Warning: AliveCorKitLite internal.
///
/// </blockquote>
SWIFT_CLASS("_TtC15AliveCorKitLite24ActivityLevelRecordModel")
@interface ActivityLevelRecordModel : NSObject
- (nonnull instancetype)initWithActivityId:(NSString * _Nullable)activityId name:(NSString * _Nullable)name note:(NSString * _Nullable)note OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSEntityDescription;
@class NSManagedObjectContext;
/// <blockquote>
/// Warning: AliveCorKitLite internal.
///
/// </blockquote>
SWIFT_CLASS_NAMED("Configuration")
@interface Configuration : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface Configuration (SWIFT_EXTENSION(AliveCorKitLite))
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

@class Feature;
@class NSSet;
@interface Configuration (SWIFT_EXTENSION(AliveCorKitLite))
- (void)addFeaturesObject:(Feature * _Nonnull)value;
- (void)removeFeaturesObject:(Feature * _Nonnull)value;
- (void)addFeatures:(NSSet * _Nonnull)values;
- (void)removeFeatures:(NSSet * _Nonnull)values;
@end

@class NSNumber;
@interface Configuration (SWIFT_EXTENSION(AliveCorKitLite))
@property (nonatomic, copy) NSString * _Nullable algVersion;
@property (nonatomic, copy) NSString * _Nullable clientId;
@property (nonatomic, copy) NSDate * _Nullable expirationDate;
@property (nonatomic, copy) NSDate * _Nullable lastUpdateDate;
@property (nonatomic, strong) NSNumber * _Nullable phoneHomeFrequency;
@property (nonatomic, strong) NSSet * _Nullable features;
@end

/// <blockquote>
/// Warning: AliveCorKitLite internal.
///
/// </blockquote>
SWIFT_CLASS("_TtC15AliveCorKitLite15ConnectionModel")
@interface ConnectionModel : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface NSDateFormatter (SWIFT_EXTENSION(AliveCorKitLite))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSDateFormatter * _Nonnull rfc3339WithSubSecondsDateFormatter;)
+ (NSDateFormatter * _Nonnull)rfc3339WithSubSecondsDateFormatter SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSDateFormatter * _Nonnull rfc3339DateFormatter;)
+ (NSDateFormatter * _Nonnull)rfc3339DateFormatter SWIFT_WARN_UNUSED_RESULT;
@end

/// <blockquote>
/// Warning: AliveCorKitLite internal.
///
/// </blockquote>
SWIFT_CLASS_NAMED("Device")
@interface Device : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface Device (SWIFT_EXTENSION(AliveCorKitLite))
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

@interface Device (SWIFT_EXTENSION(AliveCorKitLite))
@property (nonatomic, strong) NSNumber * _Nullable checkInDurationSeconds;
@property (nonatomic, strong) NSNumber * _Nullable durationSeconds;
@property (nonatomic, copy) NSDate * _Nullable expiry;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable planId;
@property (nonatomic, strong) NSNumber * _Nullable recordingLimit;
@property (nonatomic, strong) NSNumber * _Nullable recordingsTaken;
@property (nonatomic, copy) NSDate * _Nullable registeredAt;
@property (nonatomic, copy) NSString * _Nullable serialNumber;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable teamId;
@property (nonatomic, copy) NSDate * _Nullable lastUpdateDate;
@end

/// <blockquote>
/// Warning: AliveCorKitLite internal.
///
/// </blockquote>
SWIFT_CLASS("_TtC15AliveCorKitLite11DeviceModel")
@interface DeviceModel : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable status;
@property (nonatomic, readonly, copy) NSString * _Nullable serialNumber;
@property (nonatomic, readonly) BOOL isActive;
@property (nonatomic, readonly) BOOL isStale;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// <blockquote>
/// Warning: AliveCorKitLite internal.
///
/// </blockquote>
SWIFT_CLASS_NAMED("EcgRecord")
@interface EcgRecord : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface EcgRecord (SWIFT_EXTENSION(AliveCorKitLite))
- (void)addSymptoms:(NSSet * _Nonnull)values;
- (void)removeSymptoms:(NSSet * _Nonnull)values;
@end

@interface EcgRecord (SWIFT_EXTENSION(AliveCorKitLite))
@property (nonatomic, copy) NSString * _Nullable atcEnhancedFilePath;
@property (nonatomic, copy) NSString * _Nullable atcOriginalFilePath;
@property (nonatomic) int32_t bpm;
@property (nonatomic, copy) NSString * _Nullable clientId;
@property (nonatomic, copy) NSString * _Nullable device;
@property (nonatomic, copy) NSString * _Nullable errorMessage;
@property (nonatomic) BOOL isInverted;
@property (nonatomic, copy) NSString * _Nullable kaiResult;
@property (nonatomic, copy) NSString * _Nullable kaiVersion;
@property (nonatomic) int16_t leadsConfig;
@property (nonatomic) BOOL needsUpload;
@property (nonatomic) BOOL needsUploadActivity;
@property (nonatomic) BOOL needsUploadSymptoms;
@property (nonatomic, copy) NSString * _Nullable publicId;
@property (nonatomic, copy) NSDate * _Nullable recordedAtISO8601;
@property (nonatomic) BOOL requestQt;
@property (nonatomic) int32_t timeZoneOffset;
@property (nonatomic, copy) NSString * _Nullable algorithmPackage;
@property (nonatomic, copy) NSString * _Nullable deviceSerialNumber;
@property (nonatomic, strong) NSSet * _Nullable symptoms;
@end

/// <blockquote>
/// Warning: AliveCorKitLite internal.
///
/// </blockquote>
SWIFT_CLASS("_TtC15AliveCorKitLite16EntitlementModel")
@interface EntitlementModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// <blockquote>
/// Warning: AliveCorKitLite internal.
///
/// </blockquote>
SWIFT_CLASS_NAMED("Feature")
@interface Feature : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface Feature (SWIFT_EXTENSION(AliveCorKitLite))
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

@interface Feature (SWIFT_EXTENSION(AliveCorKitLite))
@property (nonatomic, copy) NSDate * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable featureName;
@property (nonatomic, copy) NSString * _Nullable publicId;
@property (nonatomic, strong) Configuration * _Nullable configuration;
@end

/// <blockquote>
/// Warning: AliveCorKitLite internal.
///
/// </blockquote>
SWIFT_CLASS("_TtC15AliveCorKitLite12FeatureModel")
@interface FeatureModel : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable featureName;
@property (nonatomic, readonly, copy) NSString * _Nullable publicId;
@property (nonatomic, readonly, copy) NSDate * _Nullable createdAt;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15AliveCorKitLite10FontLoader")
@interface FontLoader : NSObject
+ (void)registerFonts;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface NSError (SWIFT_EXTENSION(AliveCorKitLite))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkDomain;)
+ (NSString * _Nonnull)sdkDomain SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)missingTokenError SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)dateFormatError SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)eventsError SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)unknownError SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)apiErrorWithPath:(NSString * _Nonnull)path code:(NSInteger)code SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)ecgRecordingError SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)invalidTokenError SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)invalidDeviceError:(NSString * _Nonnull)status :(NSString * _Nonnull)serialNumber SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)deviceNotFoundError SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, ACKCode, open) {
  ACKCodeUnknown = 1000,
  ACKCodeMissingToken = 1001,
  ACKCodeDateFormat = 1002,
  ACKCodeEvents = 1003,
  ACKCodeApi = 1004,
  ACKCodeEcgRecording = 1005,
  ACKCodeInvalidToken = 1006,
  ACKCodeInvalidDevice = 1007,
  ACKCodeDeviceNotFound = 1008,
};

/// <blockquote>
/// Warning: AliveCorKitLite internal.
///
/// </blockquote>
SWIFT_CLASS("_TtC15AliveCorKitLite23PatientCustomFieldModel")
@interface PatientCustomFieldModel : NSObject <NSSecureCoding>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL supportsSecureCoding;)
+ (BOOL)supportsSecureCoding SWIFT_WARN_UNUSED_RESULT;
+ (void)setSupportsSecureCoding:(BOOL)value;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// <blockquote>
/// Warning: AliveCorKitLite internal.
///
/// </blockquote>
SWIFT_CLASS("_TtC15AliveCorKitLite12PatientModel")
@interface PatientModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// <blockquote>
/// Warning: AliveCorKitLite internal.
///
/// </blockquote>
SWIFT_CLASS("_TtC15AliveCorKitLite14PhysicianModel")
@interface PhysicianModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// <blockquote>
/// Warning: AliveCorKitLite internal.
///
/// </blockquote>
SWIFT_CLASS("_TtC15AliveCorKitLite12SymptomModel")
@interface SymptomModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// <blockquote>
/// Warning: AliveCorKitLite internal.
///
/// </blockquote>
SWIFT_CLASS("_TtC15AliveCorKitLite18SymptomRecordModel")
@interface SymptomRecordModel : NSObject
- (nonnull instancetype)initWithSymptomId:(NSString * _Nullable)symptomId name:(NSString * _Nullable)name note:(NSString * _Nullable)note OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// <blockquote>
/// Warning: AliveCorKitLite internal.
///
/// </blockquote>
SWIFT_CLASS("_TtC15AliveCorKitLite9TeamModel")
@interface TeamModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// <blockquote>
/// Warning: AliveCorKitLite internal.
///
/// </blockquote>
SWIFT_CLASS_NAMED("TeamPatientSetting")
@interface TeamPatientSetting : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface TeamPatientSetting (SWIFT_EXTENSION(AliveCorKitLite))
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

@interface TeamPatientSetting (SWIFT_EXTENSION(AliveCorKitLite))
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable teamId;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) BOOL isVisible;
@property (nonatomic, copy) NSDate * _Nullable createdAt;
@property (nonatomic, copy) NSDate * _Nullable updatedAt;
@end

/// <blockquote>
/// Warning: AliveCorKitLite internal.
///
/// </blockquote>
SWIFT_CLASS("_TtC15AliveCorKitLite23TeamPatientSettingModel")
@interface TeamPatientSettingModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Decodes a JWT
SWIFT_CLASS_NAMED("_JWT")
@interface A0JWT : NSObject
/// token header part
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull header;
/// token body part or claims
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull body;
/// token signature part
@property (nonatomic, readonly, copy) NSString * _Nullable signature;
/// value of the <code>exp</code> claim
@property (nonatomic, readonly, copy) NSDate * _Nullable expiresAt;
/// value of the <code>expired</code> field
@property (nonatomic, readonly) BOOL expired;
/// Creates a new instance of <code>A0JWT</code> and decodes the given jwt token.
/// :param: jwtValue of the token to decode
/// :returns: a new instance of <code>A0JWT</code> that holds the decode token
+ (A0JWT * _Nullable)decodeWithJwt:(NSString * _Nonnull)jwtValue error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
